line-length = 220
target-version = "py310"

[lint]
select = ["ALL"]

ignore = [
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ARG005",
    "B007",
    "B028",
    "BLE001",
    "C901",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D202",
    "D212",
    "D413",
    "E501",
    "EM101",
    "EM102",
    "ERA001",
    "EXE001",
    "FBT002",
    "FIX002",
    "I001",
    "ICN001",
    "PD010",
    "PD901",
    "PERF401",
    "PERF403",
    "PLR09",
    "PLR2004",
    "PLR5501",
    "PLW2901",
    "PTH123",
    "Q000",
    "RET504",
    "RET505",
    "RET506",
    "RUF012",
    "S101",
    "S301",
    "S307",
    "S311",
    "S324",
    "S603",
    "S607",
    "SIM108",
    "SIM115",
    "SLF001",
    "TD002",
    "TD003",
    "T201",
    "TRY003",
    "TRY004"
]
