import array
import hashlib
import itertools

import flow_models.convert

IN_FILES = 'data/agh_2015061019_IPv4_anon/sorted'

RESULTS = {'all': {'24d26df2a70d2533': [{'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097}],
                   '8951376641729ee3': [{'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': 1}],
                   'f151efbfa70a390a': [{'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097}],
                   '2abc89bab762aeba': [{'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': 1}],
                   'd41d8cd98f00b204': [{'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': 4097}],
                   '372c1bbd739bd444': [{'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097}],
                   '3711e7810167e360': [{'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': 1}]},
           'udp': {'f6d7a54b406cbe38': [{'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097}],
                   '8951376641729ee3': [{'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': 1}],
                   '3934bba9aef55323': [{'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097}],
                   '2abc89bab762aeba': [{'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': 1}],
                   'd41d8cd98f00b204': [{'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': 4097}],
                   '98fed1716eb39ebd': [{'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097}],
                   '58c7902cf54ff596': [{'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': 1}]},
           'tcp': {'59ca6f285d30e339': [{'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': 4097}],
                   '3711e7810167e360': [{'skip_in': -1, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 0, 'count_out': 1}],
                   '939803429004969c': [{'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': 4097}],
                   '2fe69ee49b77fc8c': [{'skip_in': -1, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 4097, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 4097, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': None, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 4097, 'skip_out': 1, 'count_out': 1}],
                   'd41d8cd98f00b204': [{'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': -1, 'count_in': 1, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 0, 'count_in': 1, 'skip_out': 1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': -1, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 0, 'count_out': 4097},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': None},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': 1},
                                        {'skip_in': 1, 'count_in': 1, 'skip_out': 1, 'count_out': 4097}]}}

def product_dict(**kwargs):
    keys = kwargs.keys()
    for instance in itertools.product(*kwargs.values()):
        yield dict(zip(keys, instance))

def test_convert():
    result = array.array('Q')
    flow_models.convert.convert([IN_FILES], result, in_format='binary', out_format='extend')
    assert len(result) == 6517484 * 21
    assert hashlib.md5(result).hexdigest() == '13d9b8b7117ee6b0ab37ce14ff90075e'

    flow_models.convert.convert([IN_FILES], IN_FILES + '_4096', in_format='binary', out_format='binary', count_in=4096)
    flow_models.convert.convert([IN_FILES], IN_FILES + '_4096.csv', in_format='binary', out_format='csv_flow', count_in=4096)

    result = array.array('Q')
    flow_models.convert.convert([IN_FILES + '_4096'], result, in_format='binary', out_format='extend')
    assert len(result) == 4096 * 21
    assert hashlib.md5(result).hexdigest() == '24d26df2a70d2533c82661bab440e5b2'

    result = array.array('Q')
    flow_models.convert.convert([IN_FILES + '_4096.csv'], result, in_format='csv_flow', out_format='extend')
    assert len(result) == 4096 * 21
    assert hashlib.md5(result).hexdigest() == '24d26df2a70d2533c82661bab440e5b2'

    matrix = {
        'skip_in': [-1, 0, 1, 4097],
        'count_in': [-1, 0, None, 1, 4097],
        'skip_out': [-1, 0, 1, 4097],
        'count_out': [-1, 0, None, 1, 4097],
        'filter_expr': [None, compile('prot==6', 'tcp', 'eval'), compile('prot==17', 'udp', 'eval')],
    }

    for suffix, in_format in [('_4096', 'binary'), ('_4096.csv', 'csv_flow')]:
        for params in product_dict(**matrix):
            result = array.array('Q')
            flow_models.convert.convert([IN_FILES + suffix], result, in_format=in_format, out_format='extend', **params)
            if params['skip_in'] > 4096 or params['skip_out'] > 4096 or params['count_in'] in (-1, 0) or params['count_out'] in (-1, 0):
                assert len(result) == 0
            else:
                ha = hashlib.md5(result).hexdigest()[:16]
                prot = params['filter_expr'].co_filename if params['filter_expr'] else 'all'
                del params['filter_expr']
                assert params in RESULTS[prot][ha]


if __name__ == '__main__':
    test_convert()
